/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#003731",
        "background": "#0b1326",
        "primary": "#89ceff",
        "surface-container-low": "#131b2e",
        "primary-fixed-dim": "#89ceff",
        "outline": "#88929b",
        "on-error-container": "#ffdad6",
        "surface-tint": "#89ceff",
        "primary-container": "#0ea5e9",
        "on-secondary-fixed-variant": "#5516be",
        "on-secondary": "#3c0091",
        "on-primary-container": "#003751",
        "surface-container-high": "#222a3d",
        "on-primary-fixed-variant": "#004c6e",
        "tertiary-fixed-dim": "#4fdbc8",
        "tertiary-fixed": "#71f8e4",
        "tertiary": "#4fdbc8",
        "surface-container-highest": "#2d3449",
        "on-tertiary-fixed": "#00201c",
        "surface-container": "#171f33",
        "on-background": "#dae2fd",
        "on-surface-variant": "#bec8d2",
        "on-tertiary-container": "#003a33",
        "surface-bright": "#31394d",
        "secondary": "#d0bcff",
        "inverse-surface": "#dae2fd",
        "error": "#ffb4ab",
        "primary-fixed": "#c9e6ff",
        "surface-dim": "#0b1326",
        "on-secondary-fixed": "#23005c",
        "outline-variant": "#3e4850",
        "surface-variant": "#2d3449",
        "secondary-container": "#571bc1",
        "surface-container-lowest": "#060e20",
        "on-error": "#690005",
        "on-secondary-container": "#c4abff",
        "secondary-fixed-dim": "#d0bcff",
        "surface": "#0b1326",
        "error-container": "#93000a",
        "on-surface": "#dae2fd",
        "secondary-fixed": "#e9ddff",
        "inverse-on-surface": "#283044",
        "on-tertiary-fixed-variant": "#005048",
        "on-primary": "#00344d",
        "inverse-primary": "#006591",
        "tertiary-container": "#00ae9d",
        "on-primary-fixed": "#001e2f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "unit": "4px",
        "max-width-content": "800px",
        "gutter": "24px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "label-md": ["JetBrains Mono", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "code-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
